// <auto-generated />
using CIS174Final.Areas.Assignment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIS174Final.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20221005153931_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CIS174Final.Areas.Assignment.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestStudents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Test1",
                            Grade = "10",
                            LastName = "Name1"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Test2",
                            Grade = "9",
                            LastName = "Name2"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Test3",
                            Grade = "5",
                            LastName = "Name3"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Test4",
                            Grade = "1",
                            LastName = "Name4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
